const recipe = [
  {
    id: 1,
    image: "",
    title: "Recette au thon",
    ingredients: [
      "Farine 200gr",
      "Thon 100gr",
      "Huile d'olive 60 ml",
      "Oeufs x2",
      "Herbe a chat 15gr",
      "Bicarbonate de soude 15gr",
    ],
    steps: [
      "Prenez un bol et battez les œufs avec l'huile d'olive et l'huile de poisson. Préchauffer également le four à 180ºC, en chauffant de haut en bas.",
      "Égouttez le thon et mélanger le poisson avec la préparation précédente.",
      "Maintenant, ajoutez l'herbe à chat et continuez à battre. Ce produit, en plus d'apporter tous ses bienfaits (comme l'effet calmant), rendra l'animal encore plus désireux de dévorer le gâteau.",
      "Tamisez la farine avec le bicarbonate de soude et l'intégrer dans la pâte en l'enveloppant délicatement. Il est fondamental que la farine soit intégrale pour garantir que l'animal puisse la digérer sans problème.",
      "Graisser un moule avec de l'huile, y verser la pâte et cuire le gâteau pendant 30-45 minutes, ou jusqu'à ce qu'il soit prêt, en chauffant seulement en dessous.",
      "Quand il est prêt, sortez du four, laissez-le refroidir, démoulez-le et offrez-le à votre chat !",
    ],
  },
  {
    id: 2,
    image: "",
    title: "Recette a la viande",
    ingredients: [
      "Farine 200gr",
      "Viande hachée 100gr",
      "Huile d'olive 60 ml",
      "Carotte rapée x1",
      "Oeufs x2",
      "Bicarbonate de soude 15gr",
      "Herbe a chat 15gr",
    ],
    steps: [
      "Préchauffez le four à 180°C.",
      "Dans un bol, battre les œufs avec l'huile.",
      "Maintenant, ajoutez l'herbe à chat et continuez à battre. Ce produit, en plus d'apporter tous ses bienfaits (comme l'effet calmant), rendra l'animal encore plus désireux de dévorer votre recette",
      "Ensuite, ajoutez la viande et la carotte, et continuer à mélanger jusqu'à ce que le mélange soit homogène. Si possible, hachez la viande au préalable ou la hacher autant que possible.",
      "Maintenant, ajoutez la farine tamisée avec le bicarbonate de soude et intégrez-la avec une cuillère ou une spatule, en faisant des mouvements enveloppants.",
      "Versez la pâte dans un moule graissé d'huile et faites cuire le gâteau pour chat pendant 30-45 minutes, selon la puissance de votre four, avec la chaleur seulement en dessous.",
      "Sortez la préparation du four quand elle est cuite, laissez-la refroidir et vous pouvez la servir à votre chat !",
    ],
  },
  {
    id: 3,
    image: "",
    title: "Recette soft vegetarienne",
    ingredients: [
      "Farine 100gr",
      "Peche x1",
      "Poire x1",
      "Huile d'olive 60 ml",
      "Miel 30gr",
      "Bicarbonate de soude 15gr",
      "Herbe a chat 15gr",
    ],
    steps: [
      "Dans un bol ou un saladier, battez l'œuf avec l'huile et le miel. Préchauffez le four à 180 ºC en chauffant de haut en bas.",
      "Épluchez les fruits, épépinez-les et broyez-les en deux ou hachez-les le plus petit possible.",
      "Mélangez la purée de fruits avec la pâte. Rappelez-vous que vous pouvez remplacer ces fruits par d'autres indiqués ci-dessus et même utiliser des légumes pour chat.",
      "Maintenant, ajoutez l'herbe à chat et continuez à battre. Ce produit, en plus d'apporter tous ses bienfaits (comme l'effet calmant), rendra l'animal encore plus désireux de dévorer le gâteau.",
      "Ajoutez maintenant la farine tamisée avec le bicarbonate de soude et l'intégrer en faisant des mouvements d'enveloppement.",
      "Versez la pâte dans un moule graissé d'huile et faites cuire le gâteau pendant 30-45 minutes, en chauffant seulement en dessous.",
      "Laisser refroidir et servir.",
    ],
  },
  {
    id: 4,
    image: "",
    title: "Recette agneau et yaourt",
    ingredients: [
      "Viande d'agneau 100gr",
      "Carotte x1",
      "Yaourt nature x1",
      "Herbe a chat 15gr",
    ],
    steps: [
      "Utilisez un hachoir pour hacher la viande et les carottes.",
      "Ensuite, faites de petites boulettes de viande, rappelez-vous qu'elles doivent être petites.",
      "Maintenant, ajoutez l'herbe à chat et continuez à battre. Ce produit, en plus d'apporter tous ses bienfaits (comme l'effet calmant), rendra l'animal encore plus désireux de dévorer votre recette",
      "Enfin, il suffit d'ajouter du yaourt sur le dessus, un aliment riche en calcium et fournit également des bactéries bénéfiques, comme les probiotiques.",
      "Tamisez la farine avec le bicarbonate de soude et l'intégrer dans la pâte en l'enveloppant délicatement. Il est fondamental que la farine soit intégrale pour garantir que l'animal puisse la digérer sans problème.",
      "Graisser un moule avec de l'huile, y verser la pâte et cuire le gâteau pendant 30-45 minutes, ou jusqu'à ce qu'il soit prêt, en chauffant seulement en dessous.",
      "Quand il est prêt, sortez du four, laissez-le refroidir, démoulez-le et offrez-le à votre chat !",
    ],
  },
  {
    id: 5,
    image: "",
    title: "Recette au crustacés",
    ingredients: [
      "Crevette 50gr",
      "Oursin de mer 20gr",
      "Moules 50gr",
      "Palourdes 30gr",
      "Gambas 50gr",
      "Herbe a chat 15gr",
    ],
    steps: [
      "Créer une salade avec les produits choisis",
      "Ajouter un peu d'huile",
      "Maintenant, ajoutez l'herbe à chat et continuez à battre. Ce produit, en plus d'apporter tous ses bienfaits (comme l'effet calmant), rendra l'animal encore plus désireux de dévorer votre recette",
    ],
  },
  {
    id: 6,
    image: "",
    title: "Recette au porc",
    ingredients: [
      "Porc 100gr",
      "Miel 30gr",
      "Romarin 60 ml",
      "Herbe a chat 15gr",
    ],
    steps: [
      "Coupez le porc en petits dés, ajoutez de l'huile et saupoudrez d'un peu de romarin sur le dessus. ",
      "Maintenant, ajoutez l'herbe à chat et continuez à battre. Ce produit, en plus d'apporter tous ses bienfaits (comme l'effet calmant), rendra l'animal encore plus désireux de dévorer votre recette",
      "Laisser macérer le mélange couvert pendant 10 à 15 minutes avec un film plastique ou autre",
      " Ajoutez ensuite un peu de miel (d'origine naturelle, non traité) et servir à votre chat.",
    ],
  },
  {
    id: 7,
    image: "",
    title: "Recette au Poulet et au riz",
    ingredients: [
      "Riz brun 60gr",
      "Poulet 75gr",
      "Fromage frais 50gr",
      "Légumes divers 30gr",
      "Huile d'olive 60 ml",
      "Bicarbonate de soude 15gr",
      "Herbe a chat 15gr",
    ],
    steps: [
      "Commencez par faire bouillir le riz brun et les légumes choisis. N'oubliez pas que vous pouvez remplacer le riz par d'autres céréales bénéfiques comme l'orge, le millet ou le quinoa. Ils doivent tous être cuits de la même façon.",
      "Faites également bouillir la viande de poulet et une fois cuite, émiettez-là et coupez-là en très petits morceaux, semblables à ceux que l'on trouve dans les boîtes de conserve commerciales ou les croquettes. Si vous le souhaitez, vous pouvez utiliser de la dinde ou du veau et même laisser la viande crue. Cela dépendra directement de l'acceptation de ce type de nourriture par votre félin.",
      "Une fois la cuisson terminée, mélangez les ingrédients déjà coupés et râpés, y compris l'huile, le carbonate de calcium (industriel ou une coquille d'œuf sèche broyée) et le fromage frais. Utilisez un emporte-pièce ou vos propres mains pour créer une forme qui lui rappellera sa nourriture humide habituelle.",
      "Maintenant, ajoutez l'herbe à chat et continuez à battre. Ce produit, en plus d'apporter tous ses bienfaits (comme l'effet calmant), rendra l'animal encore plus désireux de dévorer votre recette",
      "Et voilà, la recette pour chat est prête !",
    ],
  },
  {
    id: 8,
    image: "",
    title: "Recette a la couge et au poisson",
    ingredients: [
      "Poisson 500gr",
      "Crevette 100gr",
      "Courge 100gr",
      "Riz 75gr",
      "Herbe a chat 15gr",
      "Levure de bière 10gr",
      "Oeufs x2",
    ],
    steps: [
      "Faites bouillir le riz et la citrouille.",
      "Dans une casserole séparée, faites également bouillir les deux œufs et une fois cuits, écrasez-les avec la coquille incluse, idéal pour un apport supplémentaire en calcium.",
      "Coupez le poisson en petits cubes et ajoutez-le dans la poêle en le faisant cuire légèrement pour éviter tout problème de santé.",
      "Mélangez tous les ingrédients : les cubes de poisson, les crevettes et les moules, la citrouille bouillie, les œufs hachés et le riz. Servez-vous de vos mains pour obtenir une pâte homogène.",
      "Maintenant, ajoutez l'herbe à chat et continuez à battre. Ce produit, en plus d'apporter tous ses bienfaits (comme l'effet calmant), rendra l'animal encore plus désireux de dévorer votre recette",
      "A la fin de cette recette de poisson maison, nous pouvons la conserver au congélateur à l'aide d'un tupper ou de sacs en plastique, vous en aurez assez pour plusieurs jours.",
    ],
  },
];

export default recipe;
